### ISSUE TITLE
Wrong results when using "as_euler_angles"

### ISSUE THREAD

**Issue by SimWdm** [moble/quaternion#77] opened 2018-05-03 12:30 UTC
Hi all,

I am having an issue with the "as_euler_angles" function (on python 3.5). It seems to give me wrong angles. I checked them by using the python source code given in https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles .
I include a screenshot of my issue.

Best
Simon
<img width="249" alt="issue" src="https://user-images.githubusercontent.com/32895068/39576497-95bc0122-4ede-11e8-90dd-ecca920778f2.PNG">

**Comment by moble** [comment] 2018-05-03 13:56
I see that you're new to github and presumably pretty new to coding, so I'll point out some things that you should have done differently.  I hope you'll take this in the constructive manner it's intended.

First, when talking about code, you should never use a screenshot.  Just copy and paste the actual code.  If you use a screenshot, I can't reproduce your results without manually re-entering the code, which makes it annoying for me, and leaves you less likely to get help because developers don't want to deal with that kind of thing.  Github has [nice ways to do this](https://help.github.com/articles/creating-and-highlighting-code-blocks/), as I'll demonstrate below.

Second, if you're trying to suggest that another person's code isn't doing what you expect, you should actually show why that is.  I don't know what your `quaternion_to_euler_angles` function is, how it's defined, or what it does.  Following on with the first point, you should actually provide an executable code snippet.  This is called a "minimal working example" (MWE) or a ["minimal, complete, and verifiable example" (MCVE)](https://stackoverflow.com/help/mcve).  It would be more common to see something helpful like this in a github issue:

```python
import numpy as np
import quaternion as quat

def quaternion_to_euler_angle(q0, q1, q2, q3):
    # whatever you actually did here

q = np.array([ 0.99996885, -0.00562096,  0.00491871,  0.00255047])
print(np.linalg.norm(q))
print(quaternion_to_euler_angle(q[0], q[1], q[2], q[3]))
print(quat.as_euler_angles(quat.as_quat_array(q)))
```

And then you should show the results, again, by copying and pasting.

Third, you shouldn't claim that somebody's code is wrong just because it's not doing what *you* expected.  Again, this makes developers less likely to help you, and more likely to just grumble that you haven't tried very hard, then just close the issue.  If you have an argument for why what you're expecting is actually *correct* in some real sense, then you should try to provide that argument and not just blame someone else's code.  But first, you should try to understand their code, which brings us to...

Fourth, you should read the documentation.  I see that you're using ipython.  You can just run `quat.as_euler_angles?` (with the question mark), and it will tell you what this function does.  It's evidently not what you think.

Fifth, if you have a reference that you use to claim that there's a right way to do things (like Wikipedia's terrible article), you should actually read it.  The article points out that it uses "the JPL quaternion convention", which is not used by this package.  (It's also not actually well defined, and extremely uncommon in any case.)  The article also describes its rotations as "the **Body 3-2-1** sequence".  These should indicate to you that the article has made certain choices.  They are not the same choices I have made.  (See my fourth point above.)

Sixth, before you open an issue, you should search the issues (not just the open ones) for similar issues.  You might find that an error in code has been fixed already, and you just need to update your version.  Or you might find other people who have found a workaround that you could use.  Or you might find that people have actually brought this sort of thing up before, and it turns out that it's not a mistake at all.  For example, if you [search through the this repo's issues for Euler angles](https://github.com/moble/quaternion/issues?utf8=%E2%9C%93&q=is%3Aissue+euler+angles), you would find two issues that made similar complaints [here](#67) and [here](#71).  You could then read my responses to those and find that there are numerous ways to interpret Euler angles.  I have chosen one and documented it clearly.

---

So putting that all together, you should by now see the resolution to your problem.  No, the results you got were not wrong; they were just different from what you expected.  If you want to use different conventions for Euler angles, feel free to copy my function and adjust it to suit your needs.  But of course, you should really try to avoid Euler angles.

**Closed by moble** 2018-05-03 13:56 UTC
